baseurl = "https://lsimopoulos.github.io/"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsStyle = "monokai" # Use "igor" for light backgrounds
title = "Leonidas Simopoulos's blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "lsimopoulos"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-61788978-2"
theme = "hugo-minimalist-theme"



[params]
    site_author = "Leonidas Simopoulos"
    site_description = "The odyssey of a greek geek programmer."
    location = "Sweden"
    # Link custom assets relative to /static
    avatar = "img/profile-image.jpg"
    header_background = "img/desk.jpg"
    header_title = "My odyssey into programming"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "leonsim83"
    facebook  = ""
    linkedin  = "leonidassimopoulos"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "lsimopoulos"
    gplus     = "https://plus.google.com/u/0/111373413352934032664"
	
[taxonomies]
   tag = "tags"
   category = "categories"